apiVersion: batch/v1
kind: Job
metadata:
  name: free
  # generateName: free-
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: dockerimg
        image: mollyy/mp12_image
        env:
          - name: DATASET
            value: "mnist"
          - name: TYPE
            value : "ff"
      restartPolicy: Never
  backoffLimit: 4
